spring:
  application:
    name: mcp-test-client
  ai:
    openai:
      api-key: abc123
      base-url: http://localhost:1234
      chat:
        options:
          model: qwen
    mcp:
      client:
        name: my-mcp-client
        version: 1.0.0
        request-timeout: 30s
        type: ASYNC
        sse:
          connections:
            server1:
              url: http://localhost:8081
        stdio:
          servers-configuration: classpath:filesystem.json
rag:
  chunk-url: http://172.30.7.31
  api-key: ragflow-YzNDdjZDNlZjI5MjExZWY4ODJmMDI0Mm